version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ping
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend (Quarkus)
  backend:
    build:
      context: ./ping_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/ping
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./ping_backend:/app
    command: ./mvnw quarkus:dev

  # Frontend (React + Vite)
  frontend:
    build:
      context: ./ping_front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    volumes:
      - ./ping_front:/app
      - /app/node_modules

volumes:
  postgres_data:
